export const HappeningData = [
  {
    id: 1,
    title: "Ronaldo",
    category: "Sports",
    trending: true,
    posts: 65400,
  },
  {
    id: 2,
    title: "Little Marco",
    category: "Politics",
    trending: true,
    posts: 5554,
  },
  {
    id: 3,
    title: "Shameful",
    category: "Politics",
    trending: true,
    posts: 97600,
  },
  {
    id: 4,
    title: "Bondi",
    category: "Politics",
    trending: true,
    posts: 626000,
  },
  {
    id: 5,
    title: "Burna Boy",
    category: "Music",
    trending: true,
    posts: 32800,
  },
  {
    id: 6,
    title: "Natasha",
    category: "Politics",
    trending: true,
    posts: 59300,
  },
];

export const WhoToFollowData = [
  {
    id: 1,
    title: "Real Madrid C.F.",
    username: "@realmadrid",
    image: "/assets/friends/friend1.jpg",
  },
  {
    id: 2,
    title: "Abraham Okah(information Center)",
    username: "@ArahamOkah2",
    image: "/assets/friends/friend2.jpg",
  },
  {
    id: 3,
    title: "SusDrones.pi",
    username: "@SusDrones",
    image: "/assets/friends/friend3.jpg",
  },
  {
    id: 4,
    title: "Richard Afanyu",
    username: "@Afanyu05",
    image: "/assets/friends/friend4.jpg",
  },
  {
    id: 5,
    title: "Ndakwah Blario",
    username: "@Genda",
    image: "/assets/friends/friend5.jpg",
  },
];

export const PostsData = [
  {
    id: 1,
    userImage: "/assets/friends/friend1.jpg",
    user: "Elon Musk",
    username: "@elonmusk",
    time: "3h",
    desc: "Watch this carefully. Very Important.",
    postImage: "/assets/posts/post1.jpg",
    hashtags: [],
    comments: 38000,
    retweets: 23000,
    likes: 100000,
    engagement: 373000000,
    verified: true,
    following: true,
  },
  {
    id: 2,
    userImage: "/assets/friends/friend2.jpg",
    user: "PiWhales",
    username: "@PiWhales",
    time: "Feb 26",
    desc: `Who will be the "King of Crypto" this 2025?`,
    postImage: "/assets/posts/post2.jpg",
    hashtags: ["#PiNetwork", "$PI", "#Bitcoin", "$BTC"],
    comments: 8000,
    retweets: 300,
    likes: 10000,
    engagement: 37000,
    verified: true,
    following: false,
  },
  {
    id: 3,
    userImage: "/assets/friends/friend3.jpg",
    user: "Richard Afanyu",
    username: "@Afany05",
    time: "Sep 15, 2024",
    desc: "For those who read my copy, your feedback means a lot to me. For those who dont, Fell free to go check them out on my profile",
    hashtags: [],
    comments: 0,
    retweets: 0,
    likes: 0,
    engagement: 11,
    verified: false,
    following: true,
  },
];
